### ISSUE TITLE
Revisit error/panic handling in Begin/End blocker

### ISSUE THREAD

**Issue by alpe** [confio/tgrade#32]
Follow up on https://github.com/confio/tgrade/pull/31#discussion_r616153388
See also:
https://github.com/confio/tgrade/pull/31#discussion_r616154009

Context:
Any unhandled panic would be stopping the node. But there may be no way to recover so that stopping the node is the right thing.

**Comment by ethanfrey** [comment]
This is a question about robustness. Maybe we can have a compile-time flag for this.

On tests and testnets, I want this fail-fast behavior.
On mainnet, I would rather just log the error. We can continue with a semi-broken chain and perform a migration to fix it rather than halt the chain with no chance of recovery.

Can you add a compile-time flag around this behavior? (set var via the -X thing). Default is set, panic on error can be disabled when preparing mainnet binary

**Comment by daniellarita** [comment]
Hi @alpe can you explain the value of doing this for Mainnet MVP and what the estimation is?

**Comment by ethanfrey** [comment]
Currently, if there is any error when running the staking contract, then the chain will halt.

This change would mean the chain would continue, log an error (which may or may not be seen), and just not update the validator set until we can upgrade the contract (which will still be possible as the chain will be live).

It would make upgrades on the most critical contracts safer, and is good to have. I am not sure how important it is for mainnet, but I also think it is relatively small to do, and would be nice to have if it doesn't blow up the scope much

**Comment by alpe** [comment]
I took another look at the current implementation:
1) [begin block callback](https://github.com/confio/tgrade/blob/v0.10.0-rc1/x/twasm/abci.go#L70)
 error or panic -> logged only, state reverted
 2) [end block callback](https://github.com/confio/tgrade/blob/v0.10.0-rc1/x/twasm/abci.go#L96)
  error or panic -> logged only, state reverted
 3) [valset updater callback](https://github.com/confio/tgrade/blob/v0.10.0-rc1/x/poe/abci.go#L35)
   error or panic will halt the node
 
I would change 3) now to also handle errors and panics to the logger.

Fail fast artifacts are bit more work though as we use the same artifacts currently. I
